platform: linux

image_resource:
  type: docker-image
  source:
    repository: java

inputs:
  - name: cf-demo
outputs: 
  - name: cf-demo-outputs

run:
  dir: cf-demo
  path: ./mvnw
  args:
    - install
