platform: linux

image_resource:
  type: docker-image
  source:
    repository: java

inputs:
  - name: cf-demo
outputs:
  - name: artifact-dir

run:
  dir: cf-demo
  path: sh
  args:
    - -c
    - |
      ./mvnw clean install
      mkdir ../artifact-dir > list.txt
      cp ./target/app.jar ../artifact-dir >> list.txt
      echo EYECATCHER $PWD >> list.txt
      find . >> list.txt
      echo EYECATCHER $PWD/artifact-dir >> list.txt
      find ../artifact-dir >> list.txt
      cat list.txt
