platform: linux

image_resource:
  type: docker-image
  source:
    repository: java


inputs:
  - name: cf-demo
outputs:
  - name: artifact-dir

run:
  dir: cf-demo
  path: sh
  args:
    - -c
    - |
      echo EYECATCHER $PWD > list-dirs.txt
      find . >> list-dirs.txt
      echo EYECATCHER $PWD (back one) >> list-dirs.txt
      find .. >> list-dirs.txt
      echo EYECATCHER $PWD (back one) two list-dirs.txt
      find ../.. >> list-dirs.txt
      cat list-dirs.txt
