resources:
  - name: cf-demo
    type: git
    source:
      uri: https://github.com/cloudtraining/cf-demo
      branch: concourse
  - name: cf-dev
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: student@cloudtraining.io
      password: Welcome123!
      organization: cloudtraining.io
      space: development

jobs:
  - name: demo-app
    plan:
      - get: cf-demo
        trigger: true
      - task: tests
        file: cf-demo/.concourse.yml
      - put: cf-dev
        params:
          manifest: cf-demo/.cloudfoundry.yml
