resources:
  - name: cf-demo
    type: git
    source:
      uri: https://github.com/cloudtraining/cf-demo
      branch: concourse
  - name: cf-development
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: student@cloudtraining.io
      password: Welcome123!
      organization: cloudtraining.io
      space: development

jobs:
  - name: demo-app
    plan:
      - get: cf-demo
        trigger: true
      - task: build-and-test
        file: cf-demo/.concourse.yml
      - task: list-directories
        file: cf-demo/list-dirs.yml
      - put: cf-development
        params:
          manifest: cf-demo/.cloudfoundry-concourse.yml
          path: artifact-dir
